### PR TITLE
Add default types for common needs

### PR DESCRIPTION
**Pull request by matthewp**
This adds the following:

* type.String
* type.Number
* type.Boolean
* type.Date
* type.Integer
* type.ToString
* type.ToNumber
* type.ToBoolean
* type.ToDate
* type.ToInteger

As outlined in https://github.com/canjs/canjs/issues/5309

Omitted from this PR are:

* type.Object
* type.Array
* type.DeepObservable

Because of circular dependencies we can't have `can-type` importing
can-observable-object, can-observable-array, or can-deep-observable.

Because of tree-shaking we also can't have those types *add* the types
to the `type.` namespace. It would only work if the user was already
importing `ObservableObject`, for example. If they are already importing
ObservableObject, they already have a strict type to use.

This leaves open the possibility of a *converting* type on
`ObservableObject`, etc. This brings up the naming issue. To keep in
line with this PR you would expect `ObservableObject.ToObject`. I think
we should first consider an alternative to the [converting type
names](https://github.com/canjs/canjs/issues/5309#issuecomment-539512929),
for example perhaps `ObservableObject.CoercedObject` would be better?

### CODE REVIEW

**Comment by matthewp** [comment]
@phillipskevin Would be good to get your input on the above 👆

**Comment by phillipskevin** [comment]
Thanks for thinking this through. I agree that ObservableObject.ToObservableObject would be confusing.

Let's go with CoercedNumber, etc. I think this is most likely to mean the same thing to the highest number of users.

**Comment by justinbmeyer** [comment]
I think we avoided coerce previously because folks might have trouble spelling it.

**Comment by justinbmeyer** [comment]
I’m not sure ObservableObject.ToObservableObject would be confusing given all the other “To” types

**Comment by justinbmeyer** [comment]
Does Interger work with can-query-logic?

**Comment by matthewp** [comment]
Seems like there's a lack of consensus here. I think we're between these:

* ToNumber / ToObservableObject
* CoercedNumber / CoercedObservableObject

Let me know which one is chosen.

**Comment by phillipskevin** [comment]
I like `Coerced` because our observables and all extended types can have `Coerced` as a static property, like:

- `type: ObservableObject.Coerced`
- `type: MyObject.Coerced`
- `type: ObservableArray.Coerced`
- `type: MyArray.Coerced`

`To` is obviously easier to spell, but `MyObject.To` doesn't really make sense and `MyObject.ToMyObject` would require us to name this property differently for each type, which makes documentation difficult.

We are going to do a user test specifically around these new type changes in the next couple weeks. I think we should use `Coerced` for now and see if users have issues with it.

**Comment by matthewp** [comment]
@phillipskevin does this mean `type.CoercedNumber` as well?

**Comment by matthewp** [comment]
Punting on this for the time being.

**Pull request closed without merging**
